#!/bin/bash
rsync -avz --exclude "config.php" --exclude ".git" --exclude ".sass-cache" ../web/* www-data@eldon:/var/www/bengdb/web/

ssh www-data@eldon <<'ENDSSH'
rm -rf /var/www/bengdb/web/cache/*
ENDSSH
